name: Deploy MultiK8s
on:
 push:
   branches:
     - main
 
env:
 SHA: $(git rev-parse HEAD)
 
jobs:
 build:
   runs-on: ubuntu-latest
 
   permissions:
     contents: 'read'
     id-token: 'write'
 
   steps:
     - uses: actions/checkout@v3
 
     - name: Test
       run: |-
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
         docker build -t smbrtprmnk/react-test -f ./client/Dockerfile.dev ./client
         docker run -e CI=true smbrtprmnk/react-test npm test
 
     - name: Set Identity Provider
       uses: 'google-github-actions/auth@v0'
       with:
         workload_identity_provider: 'projects/764668127582/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
         service_account: 'github-action-deployer@multi-k8s-363605.iam.gserviceaccount.com'
 
     - name: Set Project
       uses: google-github-actions/setup-gcloud@v0
       with:
         project_id: multi-k8s-363605
 
     - name: Auth
       run: |-
         gcloud --quiet auth configure-docker
 
     - name: Get Credentials
       uses: google-github-actions/get-gke-credentials@v0
       with:
         cluster_name: multi-cluster
         location: us-central1-c
 
     - name: Build
       run: |-
         docker build -t smbrtprmnk/multi-client-k8s-gh:latest -t smbrtprmnk/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
         docker build -t smbrtprmnk/multi-server-k8s-pgfix-gh:latest -t smbrtprmnk/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
         docker build -t smbrtprmnk/multi-worker-k8s-gh:latest -t smbrtprmnk/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
     - name: Push
       run: |-
         docker push smbrtprmnk/multi-client-k8s-gh:latest
         docker push smbrtprmnk/multi-server-k8s-pgfix-gh:latest
         docker push smbrtprmnk/multi-worker-k8s-gh:latest
 
         docker push smbrtprmnk/multi-client-k8s-gh:${{ env.SHA }}
         docker push smbrtprmnk/multi-server-k8s-pgfix-gh:${{ env.SHA }}
         docker push smbrtprmnk/multi-worker-k8s-gh:${{ env.SHA }}
 
     - name: Apply
       run: |-
         kubectl apply -f k8s
         kubectl set image deployments/server-deployment server=smbrtprmnk/multi-server-k8s-pgfix-gh:${{ env.SHA }}
         kubectl set image deployments/client-deployment client=smbrtprmnk/multi-client-k8s-gh:${{ env.SHA }}
         kubectl set image deployments/worker-deployment worker=smbrtprmnk/multi-worker-k8s-gh:${{ env.SHA }}
